name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: list all c files
      run: find -regex '.*/.*\.\(c\)$'
    - name: compile all programs
      run: |
          find -regex '.*/.*\.\(c\)$' -exec gcc {} \;
