name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile all programs
      run: |
          for i in **/*.c; do
          echo "$i"
          gcc "$i" -lm
          done
          for i in **/**/*.c; do
          echo "$i"
          gcc "$i" -lm
          done
